### ISSUE TITLE
Two undefined names

### ISSUE THREAD

**Issue by cclauss** [robinsloan/sentencespace#1]
flake8 testing of https://github.com/robinsloan/sentencespace on Python 2.7.14

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./textproject_server.py:327:5: F821 undefined name 'main'
    main(**vars(args))
    ^
```

**Comment by robinsloan** [comment]
Hi there! You'll have to explain `flake8` a little more. What does it do?

**Comment by cclauss** [comment]
[flake8](https://gitlab.com/pycqa) is a linter from the Python Code Quality Authority.  The PyCQA curates the development of software tools that help Python developers to find and fix code quality issues.

What flake8 is doing here is building an Abstract Syntax Tree for each of the Python files and then looking to see which variable names can not be resolved at runtime.  These undefined name have the potential of raising [NameError](https://docs.python.org/3/library/exceptions.html#NameError) at runtime.
